name: sales_activity_tracker
description: Rolodex — a daily activities tracker for salespeople to manage prospects and record interactions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  file_picker: ^6.1.1
  csv: ^6.0.0
  share_plus: ^7.2.1
  intl: ^0.19.0
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
